config/routes.rb
Rails.application.routes.draw do
  get "users/user"
  get "static_pages/home"
  get "static_pages/help"
  get "static_pages/contact"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i.freeze
  before_save{email.downcase!}
  validates :name, presence: true, length: {maximum: Settings.user.name}
  validates :email, presence: true, length: {maximum: Settings.user.email},
            format: {with: VALID_EMAIL_REGEX},
            uniqueness: true
  validates :password, presence: true,
            length: {minimum: Settings.user.password_lenght}

  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_locale

  private

  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home; end

  def help; end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def user; end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title page_title = ""
    base_title = I18n.t("title")
    page_title.empty? ? base_title : "#{page_title} | #{base_title}"
  end
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "sample app", "#", id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to t("home"), static_pages_home_path %></li>
        <li><%= link_to t("help"), static_pages_help_path %></li>
        <li><%= link_to t("contact"), static_pages_contact_path %></li>
        <li><%= link_to t("sign_up"), "#" %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title yield :title %> </title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= link_to t("eglish"), locale: :en %>
    <%= link_to t("vietnamese"), locale: :vi %>
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_pack_tag "application", "data-turbolinks-track": "reload" %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/static_pages/contact.html.erb
<% provide :title, t("contact") %>
<div class="center jumbotron">
  <h1>Welcome to the Sample App</h1>
  <h2>Hello Vu</h2>
</div>

app/views/static_pages/help.html.erb
<% provide :title, t("help") %>
<h1>StaticPages#help</h1>
<p>
  Get help on the Ruby on Rails Tutorial at the
  <a href="http://www.railstutorial.org/help">Rails Tutorial
  help page</a>.
  To get help on this sample app, see the
  <a href="http://www.railstutorial.org/book">
    <em>Ruby on Rails Tutorial</em>
  book</a>.
</p>

app/views/static_pages/home.html.erb
<% provide :title, t("home") %>
<div class="center jumbotron">
  <h1>Welcome to the Sample App</h1>
  <h2>
    This is the home page for the
    <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
    sample application.
  </h2>
  <%= link_to "Sign up now!", '#', class: "btn btn-lg btn-primary" %>
</div>